### ISSUE TITLE
[October Build 282] Failed to include Plugin.php

### ISSUE THREAD

**Issue by justin-lau** [keiosweb/oc-plugin-testsuite#2]
When I specify my plugin with `$refreshPlugins`, an error message showing PHPUnit tries to include my `Plugin.php` from `tests/fixtures/plugins/`. Because the plugin actually lives in `plguins/` the script fails.

Replacing [line 197 of OctoberPluginTestCase.php](https://github.com/keiosweb/oc-plugin-testsuite/blob/d56974289b381dee07d2ce60359b5b3e7b0d340e/OctoberPluginTestCase.php#L197) to the following works for me:

``` php
// return plugins_path().'/'.$vendor.'/'.$plugin;
return base_path().Config::get('cms.pluginsPath').'/'.$vendor.'/'.$plugin;
```

**Comment by scottbedard** [comment]
I just ran my test suite using build 282 and 283, all is working normally. Could we see the tests you're trying to run?

**Comment by justin-lau** [comment]
Sure. I was working on [an enhancement branch of the translate-plugin](https://github.com/justin-lau/translate-plugin/tree/fix-unicode-messages), trying to add some tests for it.

The `composer.json` is using my "fixed" branch of `oc-plugin-testsuite` to get it working. You would have to remove the `repositories` field in the json file to test with the original master branch.

**Comment by keiosweb** [comment]
Hey Justin, I merged those PRs and @scottbedard is checking if they are correct now. Do you visit #october channel on IRC maybe?
